<?php
/**
 * Reference-driven Widget Architecture v2 capabilities and validation.
 *
 * @package CrescoCanvas
 */
namespace CrescoCanvas\Builder;
if ( ! defined( 'ABSPATH' ) ) exit;

final class WidgetArchitectureV2 {
	const SCHEMA='cresco-widget-architecture/v2'; const VERSION=2; const META_KEY='_cresco_canvas_widget_architecture_v2';
	public static function catalog(){
		$catalog=WidgetCatalog::all();
		$slots=array(
			'tabs'=>array('mode'=>'component-per-item','label'=>'Tab panel components','legacyFallback'=>'items'),
			'accordion'=>array('mode'=>'component-per-item','label'=>'Accordion panel components','legacyFallback'=>'items'),
			'loop-grid'=>array('mode'=>'component-template','label'=>'Loop item component','context'=>'post'),
			'woo-products'=>array('mode'=>'component-template','label'=>'Product card component','context'=>'product'),
		);
		foreach($catalog as $type=>&$widget){
			$bp=is_array($widget['blueprint']??null)?$widget['blueprint']:array(); $dynamic=array();
			foreach((array)($widget['props']??array()) as $key=>$schema) if(in_array((string)($schema['type']??'string'),array('string','text','richtext','url','css','int','number'),true)) $dynamic[]=$key;
			$bp['architectureVersion']='2.0.0'; $bp['dynamicProperties']=$dynamic; $bp['dynamicSources']=array('post','meta','acf','site','user','term','woo');
			$bp['partStyleSchema']=array('targets'=>array_keys((array)($widget['parts']??array())),'properties'=>array_values((array)($widget['style']??array())),'advancedProperties'=>self::advanced_style_properties(),'states'=>array_values(array_unique(array_merge(array('normal'),(array)($widget['states']??array())))),'breakpoints'=>array('wide','desktop','laptop','tablet','mobile'));
			$bp['responsiveInheritance']=array('wide','desktop','laptop','tablet','mobile'); $bp['visualEffects']=array('blend-mode','backdrop-filter','clip-path','transform-origin','perspective','isolation');
			if(isset($slots[$type])) $bp['nestedSlots']=$slots[$type];
			if(in_array($type,array('loop-grid','woo-products'),true)) $bp['queryBuilder']=array('schema'=>'cresco-query-builder/v2','previewable'=>true,'bounded'=>true);
			if('form'===$type) $bp['formEngine']=array('schema'=>'cresco-form-engine/v2','conditionalLogic'=>true,'multiStep'=>true,'calculations'=>true,'captchaProviders'=>array('turnstile','recaptcha_v3','hcaptcha'),'fileUploads'=>true,'signedWebhooks'=>true,'storage'=>true);
			$widget['blueprint']=$bp;
		} unset($widget); return $catalog;
	}
	public static function empty_document(){return array('schema'=>self::SCHEMA,'version'=>self::VERSION,'nodes'=>array());}
	public static function sanitize_document($input,$session){
		$input=is_array($input)?$input:array(); $types=self::node_types($session); $catalog=self::catalog(); $src=is_array($input['nodes']??null)?$input['nodes']:array(); $out=self::empty_document();
		foreach(array_slice($src,0,WebsiteBuilder::MAX_NODES,true) as $id=>$cfg){$id=self::node_id($id); if(!$id||!isset($types[$id])||!is_array($cfg))continue; $type=$types[$id]; $widget=$catalog[$type]??array(); $clean=array();
			$v=self::bindings($cfg['bindings']??array(),$widget); if($v)$clean['bindings']=$v; $v=self::part_styles($cfg['partStyles']??array(),$widget); if($v)$clean['partStyles']=$v; $v=self::slots($cfg['slots']??array(),$type); if($v)$clean['slots']=$v;
			if(in_array($type,array('loop-grid','woo-products'),true)){ $v=self::query($cfg['query']??array(),$type); if($v)$clean['query']=$v; }
			if('form'===$type){$v=self::form($cfg['form']??array()); if($v)$clean['form']=$v;} if($clean)$out['nodes'][$id]=$clean;
		} return $out;
	}
	public static function subset($doc,$ids){$set=array_fill_keys(array_filter(array_map(array(self::class,'node_id'),(array)$ids)),true);$out=self::empty_document();foreach((array)($doc['nodes']??array()) as $id=>$cfg)if(isset($set[$id]))$out['nodes'][$id]=$cfg;return $out;}
	public static function advanced_style_properties(){return array('mixBlendMode','backdropFilter','clipPath','transformOrigin','perspective','isolation');}
	public static function advanced_style_enums(){return array('mixBlendMode'=>array('normal','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion','hue','saturation','color','luminosity'),'isolation'=>array('auto','isolate'));}
	private static function bindings($input,$widget){$input=is_array($input)?$input:array();$allowed=array_flip((array)($widget['blueprint']['dynamicProperties']??array()));$out=array();foreach(array_slice($input,0,60,true) as $prop=>$b){$prop=substr(preg_replace('/[^a-zA-Z0-9_-]/','',(string)$prop),0,100);if(!isset($allowed[$prop])||!is_array($b))continue;$source=sanitize_key((string)($b['source']??'post'));if(!in_array($source,array('post','meta','acf','site','user','term','woo'),true))$source='post';$format=sanitize_key((string)($b['format']??'text'));if(!in_array($format,array('text','richtext','url','number','date'),true))$format='text';$out[$prop]=array('source'=>$source,'field'=>substr(sanitize_key((string)($b['field']??'')),0,100),'key'=>substr(preg_replace('/[^a-zA-Z0-9_.\-]/','',(string)($b['key']??'')),0,160),'fallback'=>substr(sanitize_textarea_field((string)($b['fallback']??'')),0,5000),'before'=>substr(sanitize_text_field((string)($b['before']??'')),0,500),'after'=>substr(sanitize_text_field((string)($b['after']??'')),0,500),'format'=>$format);}return $out;}
	private static function part_styles($input,$widget){$input=is_array($input)?$input:array();$parts=(array)($widget['parts']??array());$allowed=array_fill_keys(array_merge((array)($widget['style']??array()),self::advanced_style_properties()),true);$out=array();foreach(array_slice($input,0,32,true) as $part=>$cfg){$part=substr(preg_replace('/[^a-zA-Z0-9_-]/','',(string)$part),0,100);if(!isset($parts[$part])||!is_array($cfg))continue;$clean=array();$v=self::style_map($cfg['base']??array(),$allowed);if($v)$clean['base']=$v;$v=self::breakpoints($cfg['responsive']??array(),$allowed);if($v)$clean['responsive']=$v;$v=self::states($cfg['states']??array(),$allowed);if($v)$clean['states']=$v;$rs=array();foreach(array('desktop','laptop','tablet','mobile') as $d){$v=self::states($cfg['responsiveStates'][$d]??array(),$allowed);if($v)$rs[$d]=$v;}if($rs)$clean['responsiveStates']=$rs;if($clean)$out[$part]=$clean;}return $out;}
	private static function style_map($input,$allowed){$out=array();$enums=self::advanced_style_enums();foreach(array_slice((array)$input,0,100,true) as $key=>$value){$key=preg_replace('/[^a-zA-Z0-9_]/','',(string)$key);if(!isset($allowed[$key]))continue;$value=WebsiteBuilder::sanitize_css_value($value);if(isset($enums[$key])&&!in_array($value,$enums[$key],true))continue;if(''!==$value)$out[$key]=$value;}return $out;}
	private static function breakpoints($input,$allowed){$out=array();foreach(array('desktop','laptop','tablet','mobile') as $d){$v=self::style_map($input[$d]??array(),$allowed);if($v)$out[$d]=$v;}return $out;}
	private static function states($input,$allowed){$out=array();foreach(array('hover','focus','active') as $s){$v=self::style_map($input[$s]??array(),$allowed);if($v)$out[$s]=$v;}return $out;}
	private static function slots($input,$type){$input=is_array($input)?$input:array();$out=array();if(in_array($type,array('tabs','accordion'),true)){$items=array();foreach(array_slice((array)($input['items']??array()),0,24,true) as $i=>$cid){$i=absint($i);$cid=absint($cid);if($i<24&&$cid)$items[(string)$i]=$cid;}if($items)$out['items']=$items;}elseif(in_array($type,array('loop-grid','woo-products'),true)){$id=absint($input['templateComponentId']??0);if($id)$out['templateComponentId']=$id;}return $out;}
	private static function query($input,$type){$input=is_array($input)?$input:array();$out=array();if('loop-grid'===$type){if(isset($input['postType']))$out['postType']=sanitize_key((string)$input['postType']);if(isset($input['postsPerPage']))$out['postsPerPage']=min(24,max(1,absint($input['postsPerPage'])));if(isset($input['preset'])){$v=sanitize_key((string)$input['preset']);$out['preset']=in_array($v,array('custom','recent','oldest','alphabetical','random'),true)?$v:'custom';}if(isset($input['order']))$out['order']='ASC'===strtoupper((string)$input['order'])?'ASC':'DESC';if(isset($input['orderby'])){$v=sanitize_key((string)$input['orderby']);$out['orderby']=in_array($v,array('date','modified','title','menu_order','rand'),true)?$v:'date';}if(isset($input['offset']))$out['offset']=min(200,max(0,absint($input['offset'])));if(isset($input['taxonomy']))$out['taxonomy']=sanitize_key((string)$input['taxonomy']);if(isset($input['term']))$out['term']=sanitize_title((string)$input['term']);if(array_key_exists('pagination',$input))$out['pagination']=rest_sanitize_boolean($input['pagination']);if(isset($input['pageParam']))$out['pageParam']=substr(sanitize_key((string)$input['pageParam']),0,32);if(isset($input['emptyMessage']))$out['emptyMessage']=substr(sanitize_text_field((string)$input['emptyMessage']),0,500);}else{if(isset($input['limit']))$out['limit']=min(24,max(1,absint($input['limit'])));if(isset($input['columns']))$out['columns']=min(6,max(1,absint($input['columns'])));if(isset($input['orderby'])){$v=sanitize_key((string)$input['orderby']);$out['orderby']=in_array($v,array('date','title','price','popularity','rating','rand','menu_order'),true)?$v:'date';}if(isset($input['order']))$out['order']='ASC'===strtoupper((string)$input['order'])?'ASC':'DESC';if(isset($input['category']))$out['category']=sanitize_title((string)$input['category']);}return $out;}
	private static function form($input){$input=is_array($input)?$input:array();$out=array();$reply=substr(sanitize_key((string)($input['replyToField']??'')),0,48);if($reply)$out['replyToField']=$reply;$conditions=array();foreach(array_slice((array)($input['conditions']??array()),0,50,true) as $field=>$c){$field=substr(sanitize_key((string)$field),0,48);if(!$field||!is_array($c))continue;$source=substr(sanitize_key((string)($c['field']??'')),0,48);$op=sanitize_key((string)($c['operator']??'equals'));if(!in_array($op,array('equals','not_equals','contains','empty','not_empty'),true))$op='equals';if($source)$conditions[$field]=array('field'=>$source,'operator'=>$op,'value'=>substr(sanitize_text_field((string)($c['value']??'')),0,2048));}if($conditions)$out['conditions']=$conditions;$steps=array();foreach(array_slice((array)($input['steps']??array()),0,12) as $step){if(!is_array($step))continue;$fields=array_values(array_filter(array_map(static function($f){return substr(sanitize_key((string)$f),0,48);},array_slice((array)($step['fields']??array()),0,50))));if(!$fields)continue;$steps[]=array('title'=>substr(sanitize_text_field((string)($step['title']??'Step')),0,160),'fields'=>$fields,'nextLabel'=>substr(sanitize_text_field((string)($step['nextLabel']??'Next')),0,80),'previousLabel'=>substr(sanitize_text_field((string)($step['previousLabel']??'Previous')),0,80));}if($steps)$out['steps']=$steps;$calculations=array();foreach(array_slice((array)($input['calculations']??array()),0,20) as $calc){if(!is_array($calc))continue;$name=substr(sanitize_key((string)($calc['name']??'')),0,48);$formula=\CrescoCanvas\Forms\FormCompletion::sanitize_formula($calc['formula']??'');if(!$name||!$formula)continue;$calculations[]=array('name'=>$name,'label'=>substr(sanitize_text_field((string)($calc['label']??ucfirst($name))),0,160),'formula'=>$formula,'decimals'=>min(6,max(0,absint($calc['decimals']??2))),'prefix'=>substr(sanitize_text_field((string)($calc['prefix']??'')),0,80),'suffix'=>substr(sanitize_text_field((string)($calc['suffix']??'')),0,80));}if($calculations)$out['calculations']=$calculations;$captcha=is_array($input['captcha']??null)?$input['captcha']:array();if(!empty($captcha['enabled'])&&!empty($captcha['siteKey']))$out['captcha']=array('enabled'=>true,'provider'=>\CrescoCanvas\Forms\FormCompletion::sanitize_provider($captcha['provider']??'turnstile'),'siteKey'=>substr(sanitize_text_field((string)$captcha['siteKey']),0,500),'action'=>substr(sanitize_key((string)($captcha['action']??'cresco_form')),0,64));return $out;}
	private static function node_types($session){$out=array();$walk=static function($nodes)use(&$walk,&$out){foreach((array)$nodes as $node){if(!is_array($node))continue;$id=self::node_id($node['id']??'');$type=sanitize_key((string)($node['type']??''));if($id&&$type)$out[$id]=$type;$walk($node['children']??array());}};$walk(is_array($session)?($session['nodes']??array()):array());return $out;}
	private static function node_id($value){$value=preg_replace('/[^a-z0-9_-]+/','-',strtolower(trim((string)$value)));return substr(trim((string)$value,'-'),0,80);}
	private function __construct(){}
}
